
info:
  description: Azdots erp config
  url: https://github.com/tuanit/azdots-erp-config
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
foo: baz

---
spring:
  profiles: cloud
  cloud:
    config:
      uri: https://github.com/tuanit/azdots-erp-config
eureka:
  instance: 
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  

---
spring:
  profiles: docker
  cloud:
    config:
      uri: https://github.com/tuanit/azdots-erp-config
eureka:
  instance: 
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
